In [45]:
def findNumber(arr, k):
    
    sorted_arr = sorted(arr)
    print sorted_arr
    maximum = 1
    for x in sorted_arr:
        if k == x:
            return "YES"
        if x >= maximum:
            if maximum > k:
                return "NO"
        else:
            maximum = x
    
    return "NO"

In [44]:
def  oddNumbers(l, r):
    
    l = range(l, r+1, 1)
    print l
    odds = []
    for number in l:
        print number
        if number%2 == 1:
            odds.append(number)
    return odds


**Question**:
Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,
between 2000 and 3200 (both included).
The numbers obtained should be printed in a comma-separated sequence on a single line.

In [37]:
import numpy as np

def find_divisible(start, end):
    
    r = np.array(range(start, end+1, 1))
    divide = np.where(r%7 == 0) #Find divisible by 7
    not_multiple = np.where(divide[0]%5 != 0) #of those, which are not multiples of 5
    both = divide[0][not_multiple[0]] #indices where both conditions are satisfied
    return r[both]

data = find_divisible(1, 100)
print data

(array([ 6, 13, 20, 27, 34, 41, 48, 55, 62, 69, 76, 83, 90, 97]),)
[ 0  1  3  4  5  6  8  9 10 11 13]
[ 6 13 27 34 41 48 62 69 76 83 97]
[ 7 14 28 35 42 49 63 70 77 84 98]


**Question:**  
Write a program which can compute the factorial of a given numbers.
The results should be printed in a comma-separated sequence on a single line.
Suppose the following input is supplied to the program:  
8  
Then, the output should be:  
40320

In [43]:
def find_factorial(number):
    
    fact = 1
    sequence = range(1, number+1, 1)
    for n in sequence:
        fact = n*fact
    return fact

find_factorial(8)

40320

**Question:**  
With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary.  
Suppose the following input is supplied to the program:  
8  
Then, the output should be:  
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [49]:
def find_squares(number):
    
    mapped_squares = {}
    r = np.array(range(1, number+1, 1)) # r = np.arange(1, number+1, 1)
    squares = r**2
    for n, square in zip(r, squares):
        mapped_squares[n] = square
    return mapped_squares

one = find_squares(8)
print one

#Alternatively:

def find_squares_2(number):
    
    r = np.array(range(1, number+1, 1))
    squares = r**2
    return dict(zip(r, squares))

two = find_squares_2(8)
print two

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


**Question:**  
Define a class which has at least two methods:  
getString: to get a string from console input  
printString: to print the string in upper case.  
Also please include simple test function to test the class methods.  

Hints:  
Use __init__ method to construct some parameters

In [60]:
class String():
    
    def __init__(self):
        self.s = ''
    
    def getString(self, _list):
        self.s = ''.join(_list)
        
    def printString(self):
        print self.s.upper()

test_obj = String()
test_obj.getString(['s','d','e'])
test_obj.printString()


SDE


**Question:**  
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.  
Note: i=0,1.., X-1; j=0,1,¡­Y-1.  
Example  
Suppose the following inputs are given to the program:  
3,5  
Then, the output of the program should be:  
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 

In [109]:
def find_array(x, y):

    xs = np.arange(0, x, 1)
    ys = np.arange(0, y, 1)
    collect = np.zeros((3,5))
    for row, element in enumerate(xs):
        current = element*ys
        collect[row] = current
    return collect

find_array(3,5)
    

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.]])

**Question:**  
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.  
  
Suppose the following input is supplied to the program:  
without,hello,bag,world  
Then, the output should be:  
bag,hello,without,world

In [133]:
def alphabetize(words):
    lower_case = [s.lower() if any(letter.isupper() for letter in s) else s for s in words]
    lower_case.sort()
    return lower_case

w = ['without','helLo','bag','WorlD', 'ALPHA']
alphabetize(w)

['alpha', 'bag', 'hello', 'without', 'world']

**Question:**  
Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.  
  
Suppose the following input is supplied to the program:  
Hello world  
Practice makes perfect  
  
Then, the output should be:  
HELLO WORLD  
PRACTICE MAKES PERFECT

In [147]:
def make_allcaps(lines):
    uppers = np.char.upper(lines)
    return uppers

def print_lines(upper):
    for element in upper:
        print element


lines = np.array([('Hello world'), ('Practice makes perfect')])
upper = make_allcaps(lines)
print_lines(upper)

HELLO WORLD
PRACTICE MAKES PERFECT


**Question:**  
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.  
  
Suppose the following input is supplied to the program:  
hello world and practice makes perfect and hello world again  
Then, the output should be:  
again and hello makes perfect practice world

In [154]:
s = 'hello world and practice makes perfect and hello world again'

def del_dups_alphabetize(sentence):
    white_space_remove = sentence.split(' ')
    del_dups = list(set(white_space_remove))
    alpha_sort = alphabetize(del_dups) # See above
    add_white_space = ' '.join(alpha_sort)   
    return add_white_space
    
del_dups_alphabetize(s)
    

'again and hello makes perfect practice world'

**Question:**  
Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.  
  
Example:  
0100,0011,1010,1001  
  
Then the output should be:  
1010  


**Question:**  
The Fibonacci Sequence is computed based on the following formula:  

f(n)=0 if n=0  
f(n)=1 if n=1  
f(n)=f(n-1)+f(n-2) if n>1  
  
Please write a program to compute the value of f(n) with a given n input.  
Example:  
If the following n is given as input to the program:  
7  
  
Then, the output of the program should be:  
13
  
Hints:  
We can define recursive function in Python.

In [8]:
#Fibonacci seq: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34,... etc

def fib(n):
    if n == 0:
        return n
    elif n == 1:
        return n
    else:
        fibonacci = fib(n-1) + fib(n-2)
        return fibonacci

print fib(7)

# For more recursion practice: Factorial

def factorial(n):
    if n == 1:
        return n
    else:
        return n*factorial(n-1)

print factorial(5)

13
120


**Question:**  
  
Write a program to solve a classic ancient Chinese puzzle:  
We count 35 heads and 94 legs among the chickens and rabbits in a farm. How many rabbits and how many chickens do we have?