In [45]:
def findNumber(arr, k):
    
    sorted_arr = sorted(arr)
    print sorted_arr
    maximum = 1
    for x in sorted_arr:
        if k == x:
            return "YES"
        if x >= maximum:
            if maximum > k:
                return "NO"
        else:
            maximum = x
    
    return "NO"

In [44]:
def  oddNumbers(l, r):
    
    l = range(l, r+1, 1)
    print l
    odds = []
    for number in l:
        print number
        if number%2 == 1:
            odds.append(number)
    return odds


**Question**:
Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,
between 2000 and 3200 (both included).
The numbers obtained should be printed in a comma-separated sequence on a single line.

In [37]:
import numpy as np

def find_divisible(start, end):
    
    r = np.array(range(start, end+1, 1))
    divide = np.where(r%7 == 0) #Find divisible by 7
    not_multiple = np.where(divide[0]%5 != 0) #of those, which are not multiples of 5
    both = divide[0][not_multiple[0]] #indices where both conditions are satisfied
    return r[both]

data = find_divisible(1, 100)
print data

(array([ 6, 13, 20, 27, 34, 41, 48, 55, 62, 69, 76, 83, 90, 97]),)
[ 0  1  3  4  5  6  8  9 10 11 13]
[ 6 13 27 34 41 48 62 69 76 83 97]
[ 7 14 28 35 42 49 63 70 77 84 98]


**Question:**  
Write a program which can compute the factorial of a given numbers.
The results should be printed in a comma-separated sequence on a single line.
Suppose the following input is supplied to the program:  
8  
Then, the output should be:  
40320

In [43]:
def find_factorial(number):
    
    fact = 1
    sequence = range(1, number+1, 1)
    for n in sequence:
        fact = n*fact
    return fact

find_factorial(8)

40320

**Question:**  
With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary.  
Suppose the following input is supplied to the program:  
8  
Then, the output should be:  
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [49]:
def find_squares(number):
    
    mapped_squares = {}
    r = np.array(range(1, number+1, 1))
    squares = r**2
    for n, square in zip(r, squares):
        mapped_squares[n] = square
    return mapped_squares

one = find_squares(8)
print one

#Alternatively:

def find_squares_2(number):
    
    r = np.array(range(1, number+1, 1))
    squares = r**2
    return dict(zip(r, squares))

two = find_squares_2(8)
print two

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


**Question:**  
Define a class which has at least two methods:  
getString: to get a string from console input  
printString: to print the string in upper case.  
Also please include simple test function to test the class methods.  

Hints:  
Use __init__ method to construct some parameters

In [60]:
class String():
    
    def __init__(self):
        self.s = ''
    
    def getString(self, _list):
        self.s = ''.join(_list)
        
    def printString(self):
        print self.s.upper()

test_obj = String()
test_obj.getString(['s','d','e'])
test_obj.printString()


SDE
